name: THM Rooms

on:
  push:
    paths:
      - thm-rooms.md # Trigger only when this file changes
  workflow_dispatch: # Allow manual runs from the GitHub Actions UI

jobs:
  thm_rooms:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update README
        run: |
          pwsh ./scripts/update-readme.ps1
        shell: pwsh

      - name: Extract Links
        run: |
          pwsh ./scripts/extract-links.ps1 -InputFile "./README.md" -OutputFile "./thm-rooms-list.md"
        shell: pwsh

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md thm-rooms-list.md
          git commit -m "gh-action completed, thm-rooms added & extracted"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
